# Generated by Django 4.1.5 on 2023-12-29 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BillSoftwareapp', '0002_staff_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_hsn', models.PositiveIntegerField(null=True)),
                ('item_unit', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('item_taxable', models.CharField(max_length=255)),
                ('item_gst', models.CharField(max_length=255, null=True)),
                ('item_igst', models.CharField(max_length=255, null=True)),
                ('item_sale_price', models.PositiveIntegerField()),
                ('item_current_stock', models.PositiveBigIntegerField(default=0)),
                ('item_purchase_price', models.PositiveBigIntegerField()),
                ('item_stock_in_hand', models.PositiveBigIntegerField(default=0)),
                ('item_at_price', models.PositiveBigIntegerField(default=0)),
                ('item_date', models.DateField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
