# Generated by Django 4.2.3 on 2024-02-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0006_bankmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedebit',
            name='reference_number',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
