# Generated by Django 4.2.3 on 2024-02-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0007_alter_purchasedebit_reference_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='item_hsn',
            new_name='hsn',
        ),
    ]
