# Generated by Django 4.2.3 on 2024-02-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0008_rename_item_hsn_itemmodel_hsn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='hsn',
            new_name='item_hsn',
        ),
    ]
