# Generated by Django 4.2.3 on 2024-02-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0009_rename_hsn_itemmodel_item_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details'),
        ),
    ]
